### ISSUE TITLE
LockItem会有性能问题

### ISSUE THREAD

**Issue by lzb6666** [o0starshine0o/PagerLayout#2]
这个项目很不错，代码简洁，并且有效。唯一的问题是lockitem都使用canvas绘画会有性能问题，当然我觉得你可能并不会犯这样的错误，而是想练习canvas？我需要的PagerLayoutManager和PagerSnapHelper两个类，但是由于lockitem的性能问题，差点就放弃了这个项目，所以我建议换一种方式实现，使得demo程序看起来更高效

**Comment by o0starshine0o** [comment]
Android的view都是通过canvas绘图的，自定义一个View
```java
@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
    }
```
不清楚为什么说使用canvas绘图会有性能问题，体现在什么地方。

------

另外，如果不需要lockitem，是可以不需要添加这个库的，readme里面有介绍

**Comment by lzb6666** [comment]
```
I/Choreographer: Skipped 2 frames!  The application may be doing too much work on its main thread.
I/Choreographer: Skipped 2 frames!  The application may be doing too much work on its main thread.
```
滑动时视图会有不流畅的感觉（用的是中低端测试机），使用ImageView替换LockItem后会正常。
另外onDraw方法中有创建对象，这是不推荐的。所以我感觉上面滑动不流畅的问题会是LockItem#onDraw产生的。

**Comment by o0starshine0o** [comment]
看了下代码，的确有创建对象的操作，这是不对的，感谢提醒，回头我加上。
